# KONG_VERSION env variable should be assigned before using this docker compose file.
# Example: export KONG_VERSION="2.4.1.0-alpine"

version: '3'

volumes:
  kong_data:
    driver: local

networks:
  kong-edu-net:
    name: kong-edu-net
    driver: bridge

services:
  
  mockbin:
    networks:
    - kong-edu-net
    image: mashape/mockbin:latest
    container_name: mockbin
    hostname: mockbin
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 12s
      timeout: 6s
      retries: 3        
    restart: on-failure
    ports:
    - "8888:8080/tcp"
  
  postgres:
    image: postgres:13
    restart: on-failure
    container_name: postgres
    hostname: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 12s
      timeout: 6s
      retries: 3
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kong}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kong}
      POSTGRES_USER: ${POSTGRES_USER:-kong}
    ports:
    - 5432:5432
    volumes:
    - kong_data:/var/lib/postgresql/data
    networks:
    - kong-edu-net

  kong-migrations-bootstrap:
    image: kong/kong-gateway:${KONG_VERSION:-3.5}
    container_name: kong-migrations-bootstrap
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_PG_HOST: ${KONG_PG_HOST:-postgres}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PASSWORD: ${KONG_PASSWORD:-kong}
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
    networks:
    - kong-edu-net
    links:
    - postgres:postgres

  kong-migrations-up:
    image: kong/kong-gateway:${KONG_VERSION:-3.5}
    container_name: kong-migrations-up
    depends_on:
      kong-migrations-bootstrap:
        condition: service_completed_successfully
    restart: on-failure
    command: kong migrations up
    environment:
      KONG_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_PG_HOST: ${KONG_PG_HOST:-postgres}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PASSWORD: ${KONG_PASSWORD:-kong}
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
    networks:
    - kong-edu-net
    links:
    - postgres:postgres

  kong-migrations-finish: 
    image: kong/kong-gateway:${KONG_VERSION:-3.5}
    container_name: kong-migrations-finish
    depends_on:
      kong-migrations-up:
        condition: service_completed_successfully 
    restart: on-failure
    command: kong migrations finish
    environment:
      KONG_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_PG_HOST: ${KONG_PG_HOST:-postgres}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PASSWORD: ${KONG_PASSWORD:-kong}
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
    networks:
    - kong-edu-net
    links:
    - postgres:postgres

  kong-ee:
    image: kong/kong-gateway:$KONG_VERSION
    container_name: kong-ee
    hostname: kong-ee
    depends_on:
      kong-migrations-finish:
        condition: service_completed_successfully
    restart: always
    volumes:
    - /tmp/:/tmp
    ports:
    - 8000:8000
    - 8001:8001
    - 8002:8002
    - 8003:8003
    - 8004:8004
    - 8005:8005
    - 8006:8006
    - 8443:8443
    - 8444:8444
    - 8445:8445
    - 8446:8446
    - 8447:8447
    - 8100:8100
    command: kong start
    environment:
      KONG_DATABASE: ${KONG_DATABASE:-postgres}
      KONG_PG_HOST: ${KONG_PG_HOST:-postgres}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_VITALS: off
      KONG_STATUS_LISTEN: 0.0.0.0:8100
      KONG_PASSWORD: ${KONG_PASSWORD:-kong}
    networks:
    - kong-edu-net
    links:
    - postgres:postgres
